INSERT INTO aluno VALUES (18426581,"Claudio Almeida Martins","3B/4C","Noturno","claudio@gmail.com");
INSERT INTO aluno VALUES (18508774,"Beatriz Martins Barbosa Filho","3B/4C","Noturno","beatriz@gmail.com");
INSERT INTO aluno VALUES (18262066,"Davi Lourenço Mota","3B/4C","Noturno","davi@gmail.com");
INSERT INTO aluno VALUES (18398537,"Lucas Santos Amaral","3B/4C","Noturno","lucas@gmail.com");
INSERT INTO aluno VALUES (18269613,"Rafael Azzi Patricio","3B/4C","Noturno","rafael@gmail.com");
INSERT INTO aluno VALUES (18555471,"Renan Afonso Valentim","3B/4C","Noturno","renan@gmail.com");

INSERT INTO categoriacurso VALUES (1,"Ciências Humanas e Educação");
INSERT INTO categoriacurso VALUES (2,"Exatas");
INSERT INTO categoriacurso VALUES (3,"Geral");
INSERT INTO categoriacurso VALUES (4,"Gestão e Negócios");
INSERT INTO categoriacurso VALUES (5,"Saúde");

INSERT INTO atividade VALUES (1,"Atividade de Teste","25/10/2018","--/--/----","Análise e Desenvolvimento de Sistemas","Análise e Projetos de Sistemas II","","","","");
INSERT INTO atividade VALUES (2,"Atividade de Teste","17/11/2018","--/--/----","Análise e Desenvolvimento de Sistemas","Análise e Projetos de Sistemas II","","","","");
INSERT INTO atividade VALUES (3,"Atividade de Teste","25/10/2018","17/11/2018","Análise e Desenvolvimento de Sistemas","Análise e Projetos de Sistemas II","","","","");

INSERT INTO curso VALUES (1,"","Design de Produto","Tecnológico","Ciências Humanas e Educação");
INSERT INTO curso VALUES (2,"","Design Gráfico","Tecnológico","Ciências Humanas e Educação");
INSERT INTO curso VALUES (3,"","Direito","","Ciências Humanas e Educação");
INSERT INTO curso VALUES (4,"","Educação Física","Licenciatura","Ciências Humanas e Educação");
INSERT INTO curso VALUES (5,"","Física","Licenciatura","Ciências Humanas e Educação");
INSERT INTO curso VALUES (6,"","Fotografia","Tecnológico","Ciências Humanas e Educação");
INSERT INTO curso VALUES (7,"","História","Licenciatura","Ciências Humanas e Educação");
INSERT INTO curso VALUES (8,"","Letras - Português","Licenciatura","Ciências Humanas e Educação");
INSERT INTO curso VALUES (9,"","Letras - Português e Espanhol","Licenciatura","Ciências Humanas e Educação");
INSERT INTO curso VALUES (10,"","Letras - Português e Inglês","Licenciatura","Ciências Humanas e Educação");
INSERT INTO curso VALUES (11,"","Matemática","Licenciatura","Ciências Humanas e Educação");
INSERT INTO curso VALUES (12,"","Pedagogia","Licenciatura","Ciências Humanas e Educação");
INSERT INTO curso VALUES (13,"","Produção Audiovisual","Tecnológico","Ciências Humanas e Educação");
INSERT INTO curso VALUES (14,"","Produção Publicitária","Tecnológico","Ciências Humanas e Educação");
INSERT INTO curso VALUES (15,"","Relações Internacionais","","Ciências Humanas e Educação");
INSERT INTO curso VALUES (16,"","Segurança Privada","Tecnológico","Ciências Humanas e Educação");
INSERT INTO curso VALUES (17,"","Serviço Social","","Ciências Humanas e Educação");
INSERT INTO curso VALUES (18,"ADS","Análise e Desenvolvimento de Sistemas","Tecnológico","Exatas");
INSERT INTO curso VALUES (19,"","Arquitetura e Urbanismo","","Exatas");
INSERT INTO curso VALUES (20,"","Automação Industrial","","Exatas");
INSERT INTO curso VALUES (21,"","Ciência da Computação","","Exatas");
INSERT INTO curso VALUES (22,"","Design de Interiores","Tecnológico","Exatas");
INSERT INTO curso VALUES (23,"","Engenharia Ambiental","","Exatas");
INSERT INTO curso VALUES (24,"","Engenharia Civil","","Exatas");
INSERT INTO curso VALUES (25,"","Engenharia da Computação","","Exatas");
INSERT INTO curso VALUES (26,"","Engenharia de Produção","","Exatas");
INSERT INTO curso VALUES (27,"","Engenharia de Telecomunicações","","Exatas");
INSERT INTO curso VALUES (28,"","Engenharia Elétrica","","Exatas");
INSERT INTO curso VALUES (29,"","Engenharia Mecânica","","Exatas");
INSERT INTO curso VALUES (30,"","Engenharia Mecatrônica","","Exatas");
INSERT INTO curso VALUES (31,"","Gestão Ambiental","Tecnológico","Exatas");
INSERT INTO curso VALUES (32,"","Gestão da Tecnologia da Informação","Tecnológico","Exatas");
INSERT INTO curso VALUES (33,"","Produção Industrial","","Exatas");
INSERT INTO curso VALUES (34,"","Redes de Computadores","Tecnológico","Exatas");
INSERT INTO curso VALUES (35,"","Redes de Telecomunicações","","Exatas");
INSERT INTO curso VALUES (36,"","Ciências Econômicas","","Geral");
INSERT INTO curso VALUES (37,"ADM","Administração","","Gestão e Negócios");
INSERT INTO curso VALUES (38,"","Ciências Contábeis","","Gestão e Negócios");
INSERT INTO curso VALUES (39,"","Comércio Exterior","Tecnológico","Gestão e Negócios");
INSERT INTO curso VALUES (40,"","Eventos","","Gestão e Negócios");
INSERT INTO curso VALUES (41,"","Gestão Comercial","Tecnológico","Gestão e Negócios");
INSERT INTO curso VALUES (42,"","Gestão da Qualidade","","Gestão e Negócios");
INSERT INTO curso VALUES (43,"","Gestão de Turismo","Tecnológico","Gestão e Negócios");
INSERT INTO curso VALUES (44,"","Gestão em Recursos Humanos","Tecnológico","Gestão e Negócios");
INSERT INTO curso VALUES (45,"","Gestão Financeira","Tecnológico","Gestão e Negócios");
INSERT INTO curso VALUES (46,"","Gestão Pública","Tecnológico","Gestão e Negócios");
INSERT INTO curso VALUES (47,"","Logística","Tecnológico","Gestão e Negócios");
INSERT INTO curso VALUES (48,"","Marketing","Tecnológico","Gestão e Negócios");
INSERT INTO curso VALUES (49,"","Processos Gerenciais","Tecnológico","Gestão e Negócios");
INSERT INTO curso VALUES (50,"","Publicidade e Propaganda","","Gestão e Negócios");
INSERT INTO curso VALUES (51,"","Segurança no Trabalho","","Gestão e Negócios");
INSERT INTO curso VALUES (52,"","Turismo","","Gestão e Negócios");
INSERT INTO curso VALUES (53,"","Biomedicina","","Saúde");
INSERT INTO curso VALUES (54,"","Ciências Biológicas","Bacharelado","Saúde");
INSERT INTO curso VALUES (55,"","Educação Física","Bacharelado","Saúde");
INSERT INTO curso VALUES (56,"","Enfermagem","","Saúde");
INSERT INTO curso VALUES (57,"","Farmácia","","Saúde");
INSERT INTO curso VALUES (58,"","Fisioterapia","","Saúde");
INSERT INTO curso VALUES (59,"","Gestão Hospitalar","","Saúde");
INSERT INTO curso VALUES (60,"","Medicina","","Saúde");
INSERT INTO curso VALUES (61,"","Nutrição","","Saúde");
INSERT INTO curso VALUES (62,"","Odontologia","","Saúde");
INSERT INTO curso VALUES (63,"","Psicologia","","Saúde");
INSERT INTO curso VALUES (64,"","Radiologia","","Saúde");

INSERT INTO disciplina VALUES (1,"Matemática Aplicada","EAD","Análise e Desenvolvimento de Sistemas");
INSERT INTO disciplina VALUES (2,"Modelagem de Dados","Presencial","Análise e Desenvolvimento de Sistemas");
INSERT INTO disciplina VALUES (3,"Programação Orientada a Objetos","Presencial","Análise e Desenvolvimento de Sistemas");
INSERT INTO disciplina VALUES (4,"Programação Web","Presencial","Análise e Desenvolvimento de Sistemas");
INSERT INTO disciplina VALUES (5,"Técnicas de Desenvolvimento de Algoritmos","Presencial","Análise e Desenvolvimento de Sistemas");
INSERT INTO disciplina VALUES (6,"Análise e Projetos de Sistemas I","Presencial","Análise e Desenvolvimento de Sistemas");
INSERT INTO disciplina VALUES (7,"Banco de Dados","Presencial","Análise e Desenvolvimento de Sistemas");
INSERT INTO disciplina VALUES (8,"Redes de Computadores","EAD","Análise e Desenvolvimento de Sistemas");
INSERT INTO disciplina VALUES (9,"Engenharia de Software","Presencial","Análise e Desenvolvimento de Sistemas");
INSERT INTO disciplina VALUES (10,"Fundamentos de Estruturas de Dados","Presencial","Análise e Desenvolvimento de Sistemas");
INSERT INTO disciplina VALUES (11,"Projeto Interdisciplinar II","Presencial","Análise e Desenvolvimento de Sistemas");
INSERT INTO disciplina VALUES (12,"Técnicas de Programação","Presencial","Análise e Desenvolvimento de Sistemas");
INSERT INTO disciplina VALUES (13,"Análise e Projetos de Sistemas II","Presencial","Análise e Desenvolvimento de Sistemas");
INSERT INTO disciplina VALUES (14,"Empreendedorismo","EAD","Análise e Desenvolvimento de Sistemas");
INSERT INTO disciplina VALUES (15,"Gestão de Tecnologia da Informação","EAD","Análise e Desenvolvimento de Sistemas");
INSERT INTO disciplina VALUES (16,"Programação para Dispositivos Móveis","Presencial","Análise e Desenvolvimento de Sistemas");
INSERT INTO disciplina VALUES (17,"Projeto Interdisciplinar III","Presencial","Análise e Desenvolvimento de Sistemas");
INSERT INTO disciplina VALUES (18,"Qualidade de Software","Presencial","Análise e Desenvolvimento de Sistemas");
INSERT INTO disciplina VALUES (19,"Sistemas Cliente-Servidor","Presencial","Análise e Desenvolvimento de Sistemas");
INSERT INTO disciplina VALUES (20,"Tópicos Especiais","Presencial","Análise e Desenvolvimento de Sistemas");
INSERT INTO disciplina VALUES (21,"Aplicações para Internet","Presencial","Análise e Desenvolvimento de Sistemas");
INSERT INTO disciplina VALUES (22,"Engenharia de Requisitos","Presencial","Análise e Desenvolvimento de Sistemas");
INSERT INTO disciplina VALUES (23,"Fundamentos de Sistemas de Informação","Presencial","Análise e Desenvolvimento de Sistemas");
INSERT INTO disciplina VALUES (24,"Interface Humano-Computador","Presencial","Análise e Desenvolvimento de Sistemas");
INSERT INTO disciplina VALUES (25,"Língua Portuguesa","Presencial","Análise e Desenvolvimento de Sistemas");
INSERT INTO disciplina VALUES (26,"Modelagem de Negócios","Presencial","Análise e Desenvolvimento de Sistemas");
INSERT INTO disciplina VALUES (27,"Organização e Arquitetura de Computadores","Presencial","Análise e Desenvolvimento de Sistemas");
INSERT INTO disciplina VALUES (28,"Programação de Computadores","Presencial","Análise e Desenvolvimento de Sistemas");
INSERT INTO disciplina VALUES (29,"Projeto Interdisciplinar","Presencial","Análise e Desenvolvimento de Sistemas");
INSERT INTO disciplina VALUES (30,"Sistemas Operacionais","Presencial","Análise e Desenvolvimento de Sistemas");

INSERT INTO periodo VALUES (1,"Matutino");
INSERT INTO periodo VALUES (2,"Vespertino");
INSERT INTO periodo VALUES (3,"Noturno");
INSERT INTO periodo VALUES (4,"Diurno");
INSERT INTO periodo VALUES (5,"Integral");

INSERT INTO professor VALUES (12345678,"Tati","tati@unicid.com.br","Coordenador(a)","12345678");
INSERT INTO professor VALUES (87654321,"Almir","almir@unicid.com.br","Professor(a)","87654321");

INSERT INTO turma VALUES (1,"1B/2C");
INSERT INTO turma VALUES (2,"3B/4C");